from django.db import models

from apps.market_data.models import Instrument
from shared.models import BaseModel


class Strategy(BaseModel):
    """
    Defines a trading strategy configuration.
    Each strategy has rules, parameters, and generates signals.
    """

    STRATEGY_TYPE_CHOICES = [
        ("EMA_CROSSOVER", "EMA Crossover"),
        ("RSI", "RSI Overbought/Oversold"),
        ("VWAP", "VWAP Reversal"),
        ("ORB", "Opening Range Breakout"),
        ("MACD", "MACD Crossover"),
        ("BOLLINGER", "Bollinger Band Squeeze"),
        ("CUSTOM", "Custom Strategy"),
    ]

    TIMEFRAME_CHOICES = [
        ("1m", "1 Minute"),
        ("3m", "3 Minute"),
        ("5m", "5 Minute"),
        ("15m", "15 Minute"),
        ("30m", "30 Minute"),
        ("1h", "1 Hour"),
        ("1d", "1 Day"),
    ]

    name = models.CharField(max_length=100)
    description = models.TextField(blank=True)
    strategy_type = models.CharField(
        max_length=20,
        choices=STRATEGY_TYPE_CHOICES,
        db_index=True,
    )
    timeframe = models.CharField(
        max_length=10,
        choices=TIMEFRAME_CHOICES,
        default="15m",
    )
    parameters = models.JSONField(
        default=dict,
        help_text="Strategy-specific parameters as JSON.",
    )
    is_enabled = models.BooleanField(default=True)

    class Meta:
        db_table = "strategies"
        ordering = ["name"]

    def __str__(self) -> str:
        return f"{self.name} ({self.strategy_type})"


class StrategySignal(BaseModel):
    """
    A trading signal generated by a strategy.
    Records the signal type, price, and context at time of generation.
    """

    SIGNAL_CHOICES = [
        ("BUY", "Buy"),
        ("SELL", "Sell"),
        ("NEUTRAL", "Neutral"),
    ]

    STRENGTH_CHOICES = [
        ("STRONG", "Strong"),
        ("MODERATE", "Moderate"),
        ("WEAK", "Weak"),
    ]

    STATUS_CHOICES = [
        ("ACTIVE", "Active"),
        ("EXPIRED", "Expired"),
        ("TRIGGERED", "Triggered"),
    ]

    strategy = models.ForeignKey(
        Strategy,
        on_delete=models.CASCADE,
        related_name="signals",
    )
    instrument = models.ForeignKey(
        Instrument,
        on_delete=models.CASCADE,
        related_name="signals",
    )

    signal = models.CharField(
        max_length=10,
        choices=SIGNAL_CHOICES,
        db_index=True,
    )
    strength = models.CharField(
        max_length=10,
        choices=STRENGTH_CHOICES,
        default="MODERATE",
    )
    status = models.CharField(
        max_length=10,
        choices=STATUS_CHOICES,
        default="ACTIVE",
        db_index=True,
    )

    price_at_signal = models.DecimalField(
        max_digits=12,
        decimal_places=2,
    )
    target_price = models.DecimalField(
        max_digits=12,
        decimal_places=2,
        null=True,
        blank=True,
    )
    stop_loss = models.DecimalField(
        max_digits=12,
        decimal_places=2,
        null=True,
        blank=True,
    )

    timeframe = models.CharField(max_length=10)
    signal_time = models.DateTimeField(db_index=True)

    # Context snapshot at time of signal
    context = models.JSONField(
        default=dict,
        help_text="Indicator values and market context at signal time.",
    )

    notes = models.TextField(blank=True)

    class Meta:
        db_table = "strategy_signals"
        ordering = ["-signal_time"]
        indexes = [
            models.Index(fields=["instrument", "signal_time"]),
            models.Index(fields=["strategy", "signal_time"]),
            models.Index(fields=["signal", "status"]),
        ]

    def __str__(self) -> str:
        return (
            f"{self.strategy.name} | "
            f"{self.instrument.symbol} | "
            f"{self.signal} @ {self.price_at_signal}"
        )