from django.conf import settings
from django.db import models

from apps.market_data.models import Instrument
from shared.models import BaseModel


class Strategy(BaseModel):
    """
    Defines a trading strategy configuration.
    Each strategy has rules, parameters, and generates signals.
    """

    STRATEGY_TYPE_CHOICES = [
        ("EMA_CROSSOVER", "EMA Crossover"),
        ("RSI", "RSI Overbought/Oversold"),
        ("VWAP", "VWAP Reversal"),
        ("ORB", "Opening Range Breakout"),
        ("MACD", "MACD Crossover"),
        ("BOLLINGER", "Bollinger Band Squeeze"),
        ("CUSTOM", "Custom Strategy"),
    ]

    TIMEFRAME_CHOICES = [
        ("1m", "1 Minute"),
        ("3m", "3 Minute"),
        ("5m", "5 Minute"),
        ("15m", "15 Minute"),
        ("30m", "30 Minute"),
        ("1h", "1 Hour"),
        ("1d", "1 Day"),
    ]

    name = models.CharField(max_length=100)
    description = models.TextField(blank=True)
    strategy_type = models.CharField(
        max_length=20,
        choices=STRATEGY_TYPE_CHOICES,
        db_index=True,
    )
    timeframe = models.CharField(
        max_length=10,
        choices=TIMEFRAME_CHOICES,
        default="15m",
    )
    parameters = models.JSONField(
        default=dict,
        help_text="Strategy-specific parameters as JSON.",
    )
    is_enabled = models.BooleanField(default=True)

    class Meta:
        db_table = "strategies"
        ordering = ["name"]

    def __str__(self) -> str:
        return f"{self.name} ({self.strategy_type})"


class StrategySignal(BaseModel):
    """
    A trading signal generated by a strategy.
    Records the signal type, price, and context at time of generation.
    """

    SIGNAL_CHOICES = [
        ("BUY", "Buy"),
        ("SELL", "Sell"),
        ("NEUTRAL", "Neutral"),
    ]

    STRENGTH_CHOICES = [
        ("STRONG", "Strong"),
        ("MODERATE", "Moderate"),
        ("WEAK", "Weak"),
    ]

    STATUS_CHOICES = [
        ("ACTIVE", "Active"),
        ("EXPIRED", "Expired"),
        ("TRIGGERED", "Triggered"),
    ]

    strategy = models.ForeignKey(
        Strategy,
        on_delete=models.CASCADE,
        related_name="signals",
    )
    instrument = models.ForeignKey(
        Instrument,
        on_delete=models.CASCADE,
        related_name="signals",
    )

    # Owning user — needed for background outcome-tracking to know
    # whose Zerodha credentials to use when fetching real premiums.
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="strategy_signals",
    )

    signal = models.CharField(
        max_length=10,
        choices=SIGNAL_CHOICES,
        db_index=True,
    )
    strength = models.CharField(
        max_length=10,
        choices=STRENGTH_CHOICES,
        default="MODERATE",
    )
    status = models.CharField(
        max_length=10,
        choices=STATUS_CHOICES,
        default="ACTIVE",
        db_index=True,
    )

    price_at_signal = models.DecimalField(
        max_digits=12,
        decimal_places=2,
    )
    target_price = models.DecimalField(
        max_digits=12,
        decimal_places=2,
        null=True,
        blank=True,
    )
    stop_loss = models.DecimalField(
        max_digits=12,
        decimal_places=2,
        null=True,
        blank=True,
    )

    # Real option contract attached to this signal — same design as
    # AISignal, see that model for details.
    PRODUCT_CHOICES = [
        ("MIS", "Intraday"),
        ("NRML", "Carry Forward"),
    ]

    option_instrument = models.ForeignKey(
        Instrument,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="strategy_signals_as_option",
        help_text="The specific option contract (CE/PE, strike, expiry) recommended for this signal.",
    )
    entry_premium = models.DecimalField(
        max_digits=12,
        decimal_places=2,
        null=True,
        blank=True,
        help_text="Real option premium (LTP) when this contract was attached.",
    )
    product = models.CharField(
        max_length=10,
        choices=PRODUCT_CHOICES,
        default="MIS",
        help_text="MIS = intraday, auto square-off ~15:15-15:20 IST. NRML = carry forward until target/stop or contract expiry.",
    )

    # Outcome tracking (Step 5) — same design as AISignal.
    OUTCOME_CHOICES = [
        ("OPEN", "Open"),
        ("TARGET_HIT", "Target Hit"),
        ("STOP_HIT", "Stop Hit"),
        ("SQUARED_OFF", "Squared Off (MIS EOD)"),
        ("EXPIRED", "Expired (NRML)"),
    ]

    outcome_status = models.CharField(
        max_length=15,
        choices=OUTCOME_CHOICES,
        default="OPEN",
        db_index=True,
        help_text="Result of automated outcome tracking against the real option premium.",
    )
    outcome_price = models.DecimalField(
        max_digits=12,
        decimal_places=2,
        null=True,
        blank=True,
        help_text="Real premium at which tracking concluded.",
    )
    outcome_time = models.DateTimeField(
        null=True,
        blank=True,
        help_text="When tracking concluded.",
    )
    points_captured = models.DecimalField(
        max_digits=12,
        decimal_places=2,
        null=True,
        blank=True,
        help_text="outcome_price - entry_premium, in real option points.",
    )
    points_captured_pct = models.DecimalField(
        max_digits=8,
        decimal_places=2,
        null=True,
        blank=True,
        help_text="points_captured as a percentage of entry_premium.",
    )

    timeframe = models.CharField(max_length=10)
    signal_time = models.DateTimeField(db_index=True)

    # Context snapshot at time of signal
    context = models.JSONField(
        default=dict,
        help_text="Indicator values and market context at signal time.",
    )

    notes = models.TextField(blank=True)

    class Meta:
        db_table = "strategy_signals"
        ordering = ["-signal_time"]
        indexes = [
            models.Index(fields=["instrument", "signal_time"]),
            models.Index(fields=["strategy", "signal_time"]),
            models.Index(fields=["signal", "status"]),
        ]

    def __str__(self) -> str:
        return (
            f"{self.strategy.name} | "
            f"{self.instrument.symbol} | "
            f"{self.signal} @ {self.price_at_signal}"
        )