/** @type {import('tailwindcss').Config} */
export default {
    content: [
        "./index.html",
        "./src/**/*.{js,jsx}",
    ],
    theme: {
        extend: {
            colors: {
                primary: {
                    50: "rgb(var(--color-primary-50) / <alpha-value>)",
                    100: "rgb(var(--color-primary-100) / <alpha-value>)",
                    200: "rgb(var(--color-primary-200) / <alpha-value>)",
                    300: "rgb(var(--color-primary-300) / <alpha-value>)",
                    400: "rgb(var(--color-primary-400) / <alpha-value>)",
                    500: "rgb(var(--color-primary-500) / <alpha-value>)",
                    600: "rgb(var(--color-primary-600) / <alpha-value>)",
                    700: "rgb(var(--color-primary-700) / <alpha-value>)",
                    800: "rgb(var(--color-primary-800) / <alpha-value>)",
                    900: "rgb(var(--color-primary-900) / <alpha-value>)",
                },
                dark: {
                    50: "rgb(var(--color-dark-50) / <alpha-value>)",
                    100: "rgb(var(--color-dark-100) / <alpha-value>)",
                    200: "rgb(var(--color-dark-200) / <alpha-value>)",
                    300: "rgb(var(--color-dark-300) / <alpha-value>)",
                    400: "rgb(var(--color-dark-400) / <alpha-value>)",
                    500: "rgb(var(--color-dark-500) / <alpha-value>)",
                    600: "rgb(var(--color-dark-600) / <alpha-value>)",
                    700: "rgb(var(--color-dark-700) / <alpha-value>)",
                    800: "rgb(var(--color-dark-800) / <alpha-value>)",
                    900: "rgb(var(--color-dark-900) / <alpha-value>)",
                    950: "rgb(var(--color-dark-950) / <alpha-value>)",
                },
                green: {
                    50: "rgb(var(--color-green-50) / <alpha-value>)", 100: "rgb(var(--color-green-100) / <alpha-value>)",
                    200: "rgb(var(--color-green-200) / <alpha-value>)", 300: "rgb(var(--color-green-300) / <alpha-value>)",
                    400: "rgb(var(--color-green-400) / <alpha-value>)", 500: "rgb(var(--color-green-500) / <alpha-value>)",
                    600: "rgb(var(--color-green-600) / <alpha-value>)", 700: "rgb(var(--color-green-700) / <alpha-value>)",
                    800: "rgb(var(--color-green-800) / <alpha-value>)", 900: "rgb(var(--color-green-900) / <alpha-value>)",
                },
                red: {
                    50: "rgb(var(--color-red-50) / <alpha-value>)", 100: "rgb(var(--color-red-100) / <alpha-value>)",
                    200: "rgb(var(--color-red-200) / <alpha-value>)", 300: "rgb(var(--color-red-300) / <alpha-value>)",
                    400: "rgb(var(--color-red-400) / <alpha-value>)", 500: "rgb(var(--color-red-500) / <alpha-value>)",
                    600: "rgb(var(--color-red-600) / <alpha-value>)", 700: "rgb(var(--color-red-700) / <alpha-value>)",
                    800: "rgb(var(--color-red-800) / <alpha-value>)", 900: "rgb(var(--color-red-900) / <alpha-value>)",
                },
                yellow: {
                    50: "rgb(var(--color-yellow-50) / <alpha-value>)", 100: "rgb(var(--color-yellow-100) / <alpha-value>)",
                    200: "rgb(var(--color-yellow-200) / <alpha-value>)", 300: "rgb(var(--color-yellow-300) / <alpha-value>)",
                    400: "rgb(var(--color-yellow-400) / <alpha-value>)", 500: "rgb(var(--color-yellow-500) / <alpha-value>)",
                    600: "rgb(var(--color-yellow-600) / <alpha-value>)", 700: "rgb(var(--color-yellow-700) / <alpha-value>)",
                    800: "rgb(var(--color-yellow-800) / <alpha-value>)", 900: "rgb(var(--color-yellow-900) / <alpha-value>)",
                },
                blue: {
                    50: "rgb(var(--color-blue-50) / <alpha-value>)", 100: "rgb(var(--color-blue-100) / <alpha-value>)",
                    200: "rgb(var(--color-blue-200) / <alpha-value>)", 300: "rgb(var(--color-blue-300) / <alpha-value>)",
                    400: "rgb(var(--color-blue-400) / <alpha-value>)", 500: "rgb(var(--color-blue-500) / <alpha-value>)",
                    600: "rgb(var(--color-blue-600) / <alpha-value>)", 700: "rgb(var(--color-blue-700) / <alpha-value>)",
                    800: "rgb(var(--color-blue-800) / <alpha-value>)", 900: "rgb(var(--color-blue-900) / <alpha-value>)",
                },
                success: "#15803d",
                danger: "#b91c1c",
                warning: "#a16207",
                info: "#1d4ed8",
            },
            fontFamily: {
                sans: ["Inter", "system-ui", "sans-serif"],
                mono: ["JetBrains Mono", "monospace"],
            },
        },
    },
    plugins: [],
};
