# Generated by Django 5.2.16 on 2026-07-21 19:57

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("email_enabled", models.BooleanField(default=True)),
                ("telegram_enabled", models.BooleanField(default=False)),
                ("push_enabled", models.BooleanField(default=False)),
                ("telegram_chat_id", models.CharField(blank=True, max_length=50)),
                ("telegram_username", models.CharField(blank=True, max_length=100)),
                ("email_address", models.EmailField(blank=True, max_length=254)),
                ("notify_ai_signals", models.BooleanField(default=True)),
                ("notify_strategy_signals", models.BooleanField(default=True)),
                ("notify_price_alerts", models.BooleanField(default=True)),
                ("notify_trade_execution", models.BooleanField(default=True)),
                ("notify_market_open", models.BooleanField(default=False)),
                ("notify_market_close", models.BooleanField(default=False)),
                ("notify_daily_summary", models.BooleanField(default=True)),
                ("quiet_hours_enabled", models.BooleanField(default=True)),
                ("quiet_from", models.TimeField(default="22:00")),
                ("quiet_until", models.TimeField(default="08:00")),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_preferences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "notification_preferences",
            },
        ),
        migrations.CreateModel(
            name="Alert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("symbol", models.CharField(db_index=True, max_length=50)),
                (
                    "alert_type",
                    models.CharField(
                        choices=[
                            ("PRICE_ABOVE", "Price Above"),
                            ("PRICE_BELOW", "Price Below"),
                            ("PRICE_CROSS", "Price Crossover"),
                            ("RSI_ABOVE", "RSI Above"),
                            ("RSI_BELOW", "RSI Below"),
                            ("VOLUME_SPIKE", "Volume Spike"),
                            ("SIGNAL_BUY", "Buy Signal"),
                            ("SIGNAL_SELL", "Sell Signal"),
                        ],
                        db_index=True,
                        max_length=15,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("TRIGGERED", "Triggered"),
                            ("EXPIRED", "Expired"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        db_index=True,
                        default="ACTIVE",
                        max_length=10,
                    ),
                ),
                (
                    "target_value",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Price or indicator value to trigger alert.",
                        max_digits=12,
                    ),
                ),
                (
                    "current_value",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Last checked value.",
                        max_digits=12,
                    ),
                ),
                (
                    "message",
                    models.CharField(
                        blank=True, help_text="Custom alert message.", max_length=300
                    ),
                ),
                ("notify_email", models.BooleanField(default=True)),
                ("notify_telegram", models.BooleanField(default=False)),
                ("triggered_at", models.DateTimeField(blank=True, null=True)),
                (
                    "triggered_value",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "repeat",
                    models.BooleanField(
                        default=False, help_text="Re-arm alert after triggering."
                    ),
                ),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alerts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "alerts",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "status"], name="alerts_user_id_6a0f1d_idx"
                    ),
                    models.Index(
                        fields=["symbol", "status"], name="alerts_symbol_cc1cc1_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("AI_SIGNAL", "AI Signal"),
                            ("STRATEGY_SIGNAL", "Strategy Signal"),
                            ("PRICE_ALERT", "Price Alert"),
                            ("TRADE_EXECUTION", "Trade Execution"),
                            ("MARKET_OPEN", "Market Open"),
                            ("MARKET_CLOSE", "Market Close"),
                            ("DAILY_SUMMARY", "Daily Summary"),
                            ("SYSTEM", "System"),
                            ("INFO", "Info"),
                            ("WARNING", "Warning"),
                            ("ERROR", "Error"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("IN_APP", "In App"),
                            ("EMAIL", "Email"),
                            ("TELEGRAM", "Telegram"),
                            ("PUSH", "Push"),
                        ],
                        default="IN_APP",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("SENT", "Sent"),
                            ("READ", "Read"),
                            ("FAILED", "Failed"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("message", models.TextField()),
                (
                    "data",
                    models.JSONField(
                        default=dict,
                        help_text="Additional structured data for the notification.",
                    ),
                ),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("failed_reason", models.TextField(blank=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "notifications",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "status"], name="notificatio_user_id_8ab96f_idx"
                    ),
                    models.Index(
                        fields=["user", "notification_type"],
                        name="notificatio_user_id_63f199_idx",
                    ),
                    models.Index(
                        fields=["user", "created_at"],
                        name="notificatio_user_id_7336fd_idx",
                    ),
                ],
            },
        ),
    ]
