# Generated by Django 5.2.16 on 2026-07-19 20:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Instrument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "exchange",
                    models.CharField(
                        choices=[
                            ("NSE", "NSE"),
                            ("BSE", "BSE"),
                            ("NFO", "NFO"),
                            ("MCX", "MCX"),
                        ],
                        max_length=10,
                    ),
                ),
                ("symbol", models.CharField(max_length=50, unique=True)),
                ("trading_symbol", models.CharField(max_length=100)),
                ("instrument_token", models.BigIntegerField(unique=True)),
                ("tick_size", models.DecimalField(decimal_places=4, max_digits=10)),
                ("lot_size", models.IntegerField()),
                ("expiry", models.DateField(blank=True, null=True)),
                (
                    "strike",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("option_type", models.CharField(blank=True, max_length=2)),
            ],
            options={
                "db_table": "market_instruments",
                "ordering": ["symbol"],
            },
        ),
    ]
