# Generated by Django 5.2.16 on 2026-07-19 20:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("market_data", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="instrument",
            name="exchange_token",
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="instrument",
            name="instrument_token",
            field=models.BigIntegerField(default=0, unique=True),
        ),
        migrations.AlterField(
            model_name="instrument",
            name="lot_size",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="instrument",
            name="option_type",
            field=models.CharField(
                blank=True, choices=[("", ""), ("CE", "CE"), ("PE", "PE")], max_length=2
            ),
        ),
        migrations.AlterField(
            model_name="instrument",
            name="tick_size",
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
        migrations.CreateModel(
            name="Candle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "timeframe",
                    models.CharField(
                        choices=[
                            ("1m", "1 Minute"),
                            ("3m", "3 Minute"),
                            ("5m", "5 Minute"),
                            ("15m", "15 Minute"),
                            ("30m", "30 Minute"),
                            ("1h", "1 Hour"),
                            ("1d", "1 Day"),
                        ],
                        max_length=10,
                    ),
                ),
                ("candle_time", models.DateTimeField()),
                ("open", models.DecimalField(decimal_places=2, max_digits=12)),
                ("high", models.DecimalField(decimal_places=2, max_digits=12)),
                ("low", models.DecimalField(decimal_places=2, max_digits=12)),
                ("close", models.DecimalField(decimal_places=2, max_digits=12)),
                ("volume", models.BigIntegerField(default=0)),
                (
                    "instrument",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="market_data.instrument",
                    ),
                ),
            ],
            options={
                "db_table": "market_candles",
                "ordering": ["-candle_time"],
            },
        ),
        migrations.CreateModel(
            name="Quote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("last_price", models.DecimalField(decimal_places=2, max_digits=12)),
                ("open_price", models.DecimalField(decimal_places=2, max_digits=12)),
                ("high_price", models.DecimalField(decimal_places=2, max_digits=12)),
                ("low_price", models.DecimalField(decimal_places=2, max_digits=12)),
                ("close_price", models.DecimalField(decimal_places=2, max_digits=12)),
                ("volume", models.BigIntegerField(default=0)),
                ("oi", models.BigIntegerField(default=0)),
                (
                    "bid",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "ask",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "instrument",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quote",
                        to="market_data.instrument",
                    ),
                ),
            ],
            options={
                "db_table": "market_quotes",
            },
        ),
    ]
