# Generated by Django 5.2.16 on 2026-07-20 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("market_data", "0002_instrument_exchange_token_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="instrument",
            options={"ordering": ["symbol", "expiry", "strike"]},
        ),
        migrations.AddField(
            model_name="instrument",
            name="instrument_type",
            field=models.CharField(
                choices=[
                    ("EQ", "Equity"),
                    ("IDX", "Index"),
                    ("FUT", "Future"),
                    ("CE", "Call Option"),
                    ("PE", "Put Option"),
                ],
                db_index=True,
                default="EQ",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="quote",
            name="ask_qty",
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="quote",
            name="bid_qty",
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="quote",
            name="change",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="quote",
            name="change_percent",
            field=models.DecimalField(decimal_places=4, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name="candle",
            name="candle_time",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="candle",
            name="instrument",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="candles",
                to="market_data.instrument",
            ),
        ),
        migrations.AlterField(
            model_name="candle",
            name="timeframe",
            field=models.CharField(
                choices=[
                    ("1m", "1 Minute"),
                    ("3m", "3 Minute"),
                    ("5m", "5 Minute"),
                    ("15m", "15 Minute"),
                    ("30m", "30 Minute"),
                    ("1h", "1 Hour"),
                    ("1d", "1 Day"),
                ],
                db_index=True,
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="instrument",
            name="exchange",
            field=models.CharField(
                choices=[
                    ("NSE", "NSE"),
                    ("BSE", "BSE"),
                    ("NFO", "NFO"),
                    ("MCX", "MCX"),
                ],
                db_index=True,
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="instrument",
            name="exchange_token",
            field=models.BigIntegerField(default=0, help_text="Exchange-level token."),
        ),
        migrations.AlterField(
            model_name="instrument",
            name="expiry",
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="instrument",
            name="instrument_token",
            field=models.BigIntegerField(
                db_index=True,
                help_text="Zerodha's unique numeric token for this instrument.",
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="instrument",
            name="option_type",
            field=models.CharField(
                blank=True,
                choices=[("", "N/A"), ("CE", "CE"), ("PE", "PE")],
                db_index=True,
                default="",
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="instrument",
            name="symbol",
            field=models.CharField(
                db_index=True,
                help_text="Underlying symbol — e.g. NIFTY, RELIANCE. Not unique for derivatives.",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="instrument",
            name="trading_symbol",
            field=models.CharField(
                db_index=True,
                help_text="Zerodha trading symbol — unique per exchange e.g. NIFTY2572524000CE.",
                max_length=100,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="candle",
            unique_together={("instrument", "timeframe", "candle_time")},
        ),
        migrations.AlterUniqueTogether(
            name="instrument",
            unique_together={("exchange", "trading_symbol")},
        ),
        migrations.AddIndex(
            model_name="candle",
            index=models.Index(
                fields=["instrument", "timeframe", "candle_time"],
                name="market_cand_instrum_b9bf60_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="instrument",
            index=models.Index(
                fields=["symbol", "exchange"], name="market_inst_symbol_a33679_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="instrument",
            index=models.Index(
                fields=["symbol", "expiry", "option_type"],
                name="market_inst_symbol_5c8635_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="instrument",
            index=models.Index(
                fields=["instrument_token"], name="market_inst_instrum_801a6a_idx"
            ),
        ),
    ]
