# Generated by Django 5.2.17 on 2026-10-04 10:32

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_data', '0005_instrument_add_cds_exchange'),
    ]

    operations = [
        migrations.CreateModel(
            name='OptionSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('underlying', models.CharField(db_index=True, max_length=50)),
                ('captured_at', models.DateTimeField(db_index=True)),
                ('spot', models.DecimalField(decimal_places=2, max_digits=12)),
                ('ltp', models.DecimalField(decimal_places=2, max_digits=12)),
                ('bid', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('ask', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('volume', models.BigIntegerField(default=0)),
                ('oi', models.BigIntegerField(default=0)),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='market_data.instrument')),
            ],
            options={
                'db_table': 'market_option_snapshots',
                'ordering': ['-captured_at'],
                'indexes': [models.Index(fields=['underlying', 'captured_at'], name='market_opti_underly_542fec_idx'), models.Index(fields=['instrument', 'captured_at'], name='market_opti_instrum_f18496_idx')],
            },
        ),
    ]
