# Generated by Django 5.2.17 on 2026-10-04 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_data', '0006_option_snapshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrument',
            name='symbol',
            field=models.CharField(db_index=True, help_text='Underlying symbol — e.g. NIFTY, RELIANCE. Not unique for derivatives.', max_length=100),
        ),
    ]
