# Generated by Django 5.2.17 on 2026-10-04 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_data', '0007_widen_instrument_symbol'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instrument',
            options={'ordering': ['symbol', models.OrderBy(models.F('expiry'), nulls_first=True), models.OrderBy(models.F('strike'), nulls_first=True), 'trading_symbol']},
        ),
    ]
