# Generated by Django 5.2.16 on 2026-07-21 19:18

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        (
            "market_data",
            "0003_alter_instrument_options_instrument_instrument_type_and_more",
        ),
        ("strategies", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BacktestRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("timeframe", models.CharField(max_length=10)),
                ("from_date", models.DateField()),
                ("to_date", models.DateField()),
                (
                    "initial_capital",
                    models.DecimalField(
                        decimal_places=2, default=100000.0, max_digits=15
                    ),
                ),
                (
                    "position_size_pct",
                    models.DecimalField(
                        decimal_places=2,
                        default=10.0,
                        help_text="Percentage of capital per trade.",
                        max_digits=5,
                    ),
                ),
                (
                    "brokerage_per_trade",
                    models.DecimalField(decimal_places=2, default=20.0, max_digits=8),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("RUNNING", "Running"),
                            ("COMPLETE", "Complete"),
                            ("FAILED", "Failed"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("duration_seconds", models.FloatField(default=0)),
                ("error_message", models.TextField(blank=True)),
                ("candles_processed", models.IntegerField(default=0)),
                (
                    "instrument",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="backtest_runs",
                        to="market_data.instrument",
                    ),
                ),
                (
                    "strategy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="backtest_runs",
                        to="strategies.strategy",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="backtest_runs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "backtest_runs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BacktestResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("total_trades", models.IntegerField(default=0)),
                ("winning_trades", models.IntegerField(default=0)),
                ("losing_trades", models.IntegerField(default=0)),
                (
                    "win_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                (
                    "total_pnl",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "total_net_pnl",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "avg_pnl_per_trade",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "avg_win",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "avg_loss",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "largest_win",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "largest_loss",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "profit_factor",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                (
                    "initial_capital",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "final_capital",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "total_return_pct",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                (
                    "max_drawdown",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "max_drawdown_pct",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                (
                    "sharpe_ratio",
                    models.DecimalField(decimal_places=4, default=0, max_digits=8),
                ),
                (
                    "expectancy",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "risk_reward_ratio",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                ("consecutive_wins", models.IntegerField(default=0)),
                ("consecutive_losses", models.IntegerField(default=0)),
                (
                    "equity_curve",
                    models.JSONField(
                        default=list,
                        help_text="List of {time, capital} dicts for plotting.",
                    ),
                ),
                (
                    "run",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="result",
                        to="backtesting.backtestrun",
                    ),
                ),
            ],
            options={
                "db_table": "backtest_results",
            },
        ),
        migrations.CreateModel(
            name="BacktestTrade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "direction",
                    models.CharField(
                        choices=[("LONG", "Long"), ("SHORT", "Short")], max_length=5
                    ),
                ),
                ("quantity", models.IntegerField(default=1)),
                ("entry_price", models.DecimalField(decimal_places=2, max_digits=12)),
                ("exit_price", models.DecimalField(decimal_places=2, max_digits=12)),
                ("entry_time", models.DateTimeField()),
                ("exit_time", models.DateTimeField()),
                ("pnl", models.DecimalField(decimal_places=2, max_digits=12)),
                ("pnl_pct", models.DecimalField(decimal_places=4, max_digits=8)),
                (
                    "brokerage",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                ("net_pnl", models.DecimalField(decimal_places=2, max_digits=12)),
                ("signal", models.CharField(max_length=10)),
                ("signal_strength", models.CharField(blank=True, max_length=10)),
                ("signal_notes", models.TextField(blank=True)),
                ("signal_context", models.JSONField(default=dict)),
                (
                    "exit_reason",
                    models.CharField(
                        choices=[
                            ("SIGNAL", "Opposite Signal"),
                            ("STOP_LOSS", "Stop Loss"),
                            ("TARGET", "Target Hit"),
                            ("EOD", "End of Day"),
                            ("END_OF_DATA", "End of Data"),
                        ],
                        default="SIGNAL",
                        max_length=20,
                    ),
                ),
                (
                    "capital_after",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trades",
                        to="backtesting.backtestrun",
                    ),
                ),
            ],
            options={
                "db_table": "backtest_trades",
                "ordering": ["entry_time"],
            },
        ),
        migrations.AddIndex(
            model_name="backtestrun",
            index=models.Index(
                fields=["user", "status"], name="backtest_ru_user_id_052de1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="backtestrun",
            index=models.Index(
                fields=["strategy", "instrument"], name="backtest_ru_strateg_b333e7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="backtesttrade",
            index=models.Index(
                fields=["run", "entry_time"], name="backtest_tr_run_id_614af3_idx"
            ),
        ),
    ]
