# Generated by Django 5.2.17 on 2026-10-04 16:08

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zerodha', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveTradingAuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('action', models.CharField(choices=[('MASTER_ON', 'Master switch turned on'), ('MASTER_OFF', 'Master switch turned off'), ('ARM', 'User armed live orders'), ('DISARM', 'User disarmed live orders')], max_length=12)),
                ('detail', models.CharField(blank=True, max_length=200)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'zerodha_live_trading_audit',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LiveTradingControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('enabled', models.BooleanField(default=False)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'zerodha_live_trading_control',
            },
        ),
        migrations.CreateModel(
            name='LiveTradingArming',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('armed_at', models.DateTimeField()),
                ('expires_at', models.DateTimeField()),
                ('disarmed_at', models.DateTimeField(blank=True, null=True)),
                ('disclaimer_version', models.CharField(max_length=40)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_trading_armings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'zerodha_live_trading_armings',
                'ordering': ['-armed_at'],
                'indexes': [models.Index(fields=['user', 'expires_at'], name='zerodha_liv_user_id_97b258_idx')],
            },
        ),
    ]
