# Generated by Django 5.2.16 on 2026-07-21 18:30

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        (
            "market_data",
            "0003_alter_instrument_options_instrument_instrument_type_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Strategy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "strategy_type",
                    models.CharField(
                        choices=[
                            ("EMA_CROSSOVER", "EMA Crossover"),
                            ("RSI", "RSI Overbought/Oversold"),
                            ("VWAP", "VWAP Reversal"),
                            ("ORB", "Opening Range Breakout"),
                            ("MACD", "MACD Crossover"),
                            ("BOLLINGER", "Bollinger Band Squeeze"),
                            ("CUSTOM", "Custom Strategy"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "timeframe",
                    models.CharField(
                        choices=[
                            ("1m", "1 Minute"),
                            ("3m", "3 Minute"),
                            ("5m", "5 Minute"),
                            ("15m", "15 Minute"),
                            ("30m", "30 Minute"),
                            ("1h", "1 Hour"),
                            ("1d", "1 Day"),
                        ],
                        default="15m",
                        max_length=10,
                    ),
                ),
                (
                    "parameters",
                    models.JSONField(
                        default=dict, help_text="Strategy-specific parameters as JSON."
                    ),
                ),
                ("is_enabled", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "strategies",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="StrategySignal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "signal",
                    models.CharField(
                        choices=[
                            ("BUY", "Buy"),
                            ("SELL", "Sell"),
                            ("NEUTRAL", "Neutral"),
                        ],
                        db_index=True,
                        max_length=10,
                    ),
                ),
                (
                    "strength",
                    models.CharField(
                        choices=[
                            ("STRONG", "Strong"),
                            ("MODERATE", "Moderate"),
                            ("WEAK", "Weak"),
                        ],
                        default="MODERATE",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("EXPIRED", "Expired"),
                            ("TRIGGERED", "Triggered"),
                        ],
                        db_index=True,
                        default="ACTIVE",
                        max_length=10,
                    ),
                ),
                (
                    "price_at_signal",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "target_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "stop_loss",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("timeframe", models.CharField(max_length=10)),
                ("signal_time", models.DateTimeField(db_index=True)),
                (
                    "context",
                    models.JSONField(
                        default=dict,
                        help_text="Indicator values and market context at signal time.",
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "instrument",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="signals",
                        to="market_data.instrument",
                    ),
                ),
                (
                    "strategy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="signals",
                        to="strategies.strategy",
                    ),
                ),
            ],
            options={
                "db_table": "strategy_signals",
                "ordering": ["-signal_time"],
                "indexes": [
                    models.Index(
                        fields=["instrument", "signal_time"],
                        name="strategy_si_instrum_93e5dd_idx",
                    ),
                    models.Index(
                        fields=["strategy", "signal_time"],
                        name="strategy_si_strateg_7bbcce_idx",
                    ),
                    models.Index(
                        fields=["signal", "status"],
                        name="strategy_si_signal_3adb69_idx",
                    ),
                ],
            },
        ),
    ]
