# Generated by Django 5.2.16 on 2026-08-01 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "market_data",
            "0003_alter_instrument_options_instrument_instrument_type_and_more",
        ),
        ("strategies", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="strategysignal",
            name="entry_premium",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Real option premium (LTP) when this contract was attached.",
                max_digits=12,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="strategysignal",
            name="option_instrument",
            field=models.ForeignKey(
                blank=True,
                help_text="The specific option contract (CE/PE, strike, expiry) recommended for this signal.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="strategy_signals_as_option",
                to="market_data.instrument",
            ),
        ),
        migrations.AddField(
            model_name="strategysignal",
            name="product",
            field=models.CharField(
                choices=[("MIS", "Intraday"), ("NRML", "Carry Forward")],
                default="MIS",
                help_text="MIS = intraday, auto square-off ~15:15-15:20 IST. NRML = carry forward until target/stop or contract expiry.",
                max_length=10,
            ),
        ),
    ]
