# Generated by Django 5.2.16 on 2026-08-01 21:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("strategies", "0002_strategysignal_entry_premium_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="strategysignal",
            name="outcome_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Real premium at which tracking concluded.",
                max_digits=12,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="strategysignal",
            name="outcome_status",
            field=models.CharField(
                choices=[
                    ("OPEN", "Open"),
                    ("TARGET_HIT", "Target Hit"),
                    ("STOP_HIT", "Stop Hit"),
                    ("SQUARED_OFF", "Squared Off (MIS EOD)"),
                    ("EXPIRED", "Expired (NRML)"),
                ],
                db_index=True,
                default="OPEN",
                help_text="Result of automated outcome tracking against the real option premium.",
                max_length=15,
            ),
        ),
        migrations.AddField(
            model_name="strategysignal",
            name="outcome_time",
            field=models.DateTimeField(
                blank=True, help_text="When tracking concluded.", null=True
            ),
        ),
        migrations.AddField(
            model_name="strategysignal",
            name="points_captured",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="outcome_price - entry_premium, in real option points.",
                max_digits=12,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="strategysignal",
            name="points_captured_pct",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="points_captured as a percentage of entry_premium.",
                max_digits=8,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="strategysignal",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="strategy_signals",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
