# Generated by Django 5.2.16 on 2026-07-21 18:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        (
            "market_data",
            "0003_alter_instrument_options_instrument_instrument_type_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="PromptTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "template_type",
                    models.CharField(
                        choices=[
                            ("MARKET_ANALYSIS", "Market Analysis"),
                            ("SETUP_SCANNER", "Setup Scanner"),
                            ("OPTION_CHAIN", "Option Chain Analysis"),
                            ("RISK_ASSESSMENT", "Risk Assessment"),
                            ("TRADE_REVIEW", "Trade Review"),
                            ("NEWS_ANALYSIS", "News Analysis"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "system_prompt",
                    models.TextField(help_text="System prompt sent to the AI model."),
                ),
                (
                    "user_prompt_template",
                    models.TextField(
                        help_text="User prompt template with {placeholders}."
                    ),
                ),
                (
                    "model",
                    models.CharField(
                        default="claude-sonnet-4-6",
                        help_text="AI model to use for this template.",
                        max_length=50,
                    ),
                ),
                ("max_tokens", models.IntegerField(default=2000)),
                ("temperature", models.FloatField(default=0.3)),
                ("version", models.CharField(default="v1", max_length=20)),
                ("is_default", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "ai_prompt_templates",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="AnalysisSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "session_type",
                    models.CharField(
                        choices=[
                            ("MARKET_ANALYSIS", "Market Analysis"),
                            ("SETUP_SCANNER", "Setup Scanner"),
                            ("OPTION_CHAIN", "Option Chain Analysis"),
                            ("RISK_ASSESSMENT", "Risk Assessment"),
                            ("TRADE_REVIEW", "Trade Review"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("RUNNING", "Running"),
                            ("COMPLETE", "Complete"),
                            ("FAILED", "Failed"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                ("timeframe", models.CharField(blank=True, max_length=10)),
                (
                    "market_context",
                    models.JSONField(
                        default=dict, help_text="Market data snapshot used as input."
                    ),
                ),
                ("prompt_used", models.TextField(blank=True)),
                ("ai_response", models.TextField(blank=True)),
                (
                    "parsed_output",
                    models.JSONField(
                        default=dict,
                        help_text="Structured output parsed from AI response.",
                    ),
                ),
                ("model_used", models.CharField(blank=True, max_length=50)),
                ("tokens_used", models.IntegerField(default=0)),
                ("duration_ms", models.IntegerField(default=0)),
                ("error_message", models.TextField(blank=True)),
                (
                    "session_time",
                    models.DateTimeField(auto_now_add=True, db_index=True),
                ),
                (
                    "instrument",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="analysis_sessions",
                        to="market_data.instrument",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ai_engine.prompttemplate",
                    ),
                ),
            ],
            options={
                "db_table": "ai_analysis_sessions",
                "ordering": ["-session_time"],
            },
        ),
        migrations.CreateModel(
            name="AISignal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "signal",
                    models.CharField(
                        choices=[
                            ("BUY", "Buy"),
                            ("SELL", "Sell"),
                            ("NEUTRAL", "Neutral"),
                            ("NO_SETUP", "No Setup"),
                            ("WATCH", "Watch"),
                        ],
                        db_index=True,
                        max_length=10,
                    ),
                ),
                (
                    "confidence",
                    models.CharField(
                        choices=[
                            ("HIGH", "High"),
                            ("MEDIUM", "Medium"),
                            ("LOW", "Low"),
                        ],
                        default="MEDIUM",
                        max_length=10,
                    ),
                ),
                (
                    "confidence_score",
                    models.IntegerField(default=0, help_text="0-100 confidence score."),
                ),
                (
                    "price_at_signal",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "target_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "stop_loss",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "reasoning",
                    models.TextField(help_text="AI reasoning for this signal."),
                ),
                ("key_levels", models.JSONField(default=dict)),
                ("risks", models.JSONField(default=list)),
                ("signal_time", models.DateTimeField(db_index=True)),
                (
                    "instrument",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_signals",
                        to="market_data.instrument",
                    ),
                ),
                (
                    "session",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_signal",
                        to="ai_engine.analysissession",
                    ),
                ),
            ],
            options={
                "db_table": "ai_signals",
                "ordering": ["-signal_time"],
            },
        ),
        migrations.AddIndex(
            model_name="analysissession",
            index=models.Index(
                fields=["session_type", "session_time"],
                name="ai_analysis_session_d977c1_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="analysissession",
            index=models.Index(
                fields=["status", "session_time"], name="ai_analysis_status_9410de_idx"
            ),
        ),
    ]
