# Generated by Django 5.2.17 on 2026-09-29 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_engine', '0004_analysis_forecast_tracking'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningWorkerState',
            fields=[
                ('name', models.CharField(default='default', max_length=40, primary_key=True, serialize=False)),
                ('heartbeat_at', models.DateTimeField(null=True)),
                ('lease_until', models.DateTimeField(null=True)),
                ('result', models.JSONField(default=dict)),
            ],
        ),
        migrations.AddField(
            model_name='analysissession',
            name='paper_evaluation',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='analysissession',
            name='prompt_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='analysissession',
            name='prompt_version',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='analysissession',
            name='provider_used',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='analysissession',
            name='system_prompt_used',
            field=models.TextField(blank=True),
        ),
    ]
