# Generated by Codex for per-user encrypted AI provider credentials.
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_engine", "0005_workspace_learning_audit"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AIProviderCredential",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("provider", models.CharField(choices=[("gemini", "Gemini"), ("kimi", "Kimi"), ("claude", "Claude"), ("groq", "Groq")], max_length=20)),
                ("encrypted_api_key", models.TextField()),
                ("user", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="ai_provider_credential", to=settings.AUTH_USER_MODEL)),
            ],
            options={"db_table": "ai_provider_credentials"},
        ),
    ]
