# Generated by Django 5.2.17 on 2026-10-05 20:24

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_engine', '0006_ai_provider_credential'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('setup_strictness', models.CharField(choices=[('STRICT', 'Strict'), ('BALANCED', 'Balanced'), ('EXPLORATORY', 'Exploratory')], default='BALANCED', help_text='How readily the AI may return BUY/SELL instead of NO_SETUP. Code-level safety rules always apply.', max_length=12)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_preference', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ai_analysis_preferences',
            },
        ),
    ]
