# Generated by Django 5.2.16 on 2026-07-21 19:38

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("name", models.CharField(max_length=50, unique=True)),
                ("slug", models.SlugField(unique=True)),
                (
                    "color",
                    models.CharField(
                        default="#3B82F6",
                        help_text="Hex color code for UI display.",
                        max_length=7,
                    ),
                ),
            ],
            options={
                "db_table": "knowledge_tags",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("title", models.CharField(db_index=True, max_length=300)),
                ("slug", models.SlugField(max_length=300, unique=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("CONCEPT", "Trading Concept"),
                            ("STRATEGY", "Strategy"),
                            ("INDICATOR", "Technical Indicator"),
                            ("OPTION", "Options Theory"),
                            ("PSYCHOLOGY", "Psychology"),
                            ("RISK", "Risk Management"),
                            ("MARKET", "Market Structure"),
                            ("ZERODHA", "Zerodha Varsity"),
                            ("BOOK", "Book Notes"),
                            ("RESEARCH", "Research"),
                            ("OTHER", "Other"),
                        ],
                        db_index=True,
                        default="CONCEPT",
                        max_length=15,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("MANUAL", "Manual Entry"),
                            ("VARSITY", "Zerodha Varsity"),
                            ("BOOK", "Book"),
                            ("BLOG", "Blog/Article"),
                            ("VIDEO", "Video"),
                            ("AI", "AI Generated"),
                            ("TRANSCRIPT", "Transcript"),
                        ],
                        default="MANUAL",
                        max_length=15,
                    ),
                ),
                ("source_url", models.URLField(blank=True)),
                ("content", models.TextField()),
                (
                    "summary",
                    models.TextField(
                        blank=True, help_text="Short summary — AI generated or manual."
                    ),
                ),
                (
                    "key_points",
                    models.JSONField(default=list, help_text="List of key takeaways."),
                ),
                ("ai_summary", models.TextField(blank=True)),
                ("ai_summarized_at", models.DateTimeField(blank=True, null=True)),
                ("view_count", models.IntegerField(default=0)),
                ("is_featured", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="articles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True, related_name="articles", to="knowledge.tag"
                    ),
                ),
            ],
            options={
                "db_table": "knowledge_articles",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BookNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("title", models.CharField(max_length=200)),
                ("author", models.CharField(blank=True, max_length=200)),
                ("isbn", models.CharField(blank=True, max_length=20)),
                ("summary", models.TextField(blank=True)),
                (
                    "key_lessons",
                    models.JSONField(
                        default=list, help_text="List of key lessons from the book."
                    ),
                ),
                (
                    "rating",
                    models.IntegerField(default=0, help_text="Personal rating 1-10."),
                ),
                ("started_at", models.DateField(blank=True, null=True)),
                ("finished_at", models.DateField(blank=True, null=True)),
                (
                    "articles",
                    models.ManyToManyField(
                        blank=True, related_name="books", to="knowledge.article"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="book_notes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "knowledge_book_notes",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Prompt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("title", models.CharField(max_length=200)),
                (
                    "prompt_type",
                    models.CharField(
                        choices=[
                            ("ANALYSIS", "Market Analysis"),
                            ("RESEARCH", "Research"),
                            ("STRATEGY", "Strategy Development"),
                            ("REVIEW", "Trade Review"),
                            ("LEARNING", "Learning"),
                            ("CUSTOM", "Custom"),
                        ],
                        db_index=True,
                        default="CUSTOM",
                        max_length=15,
                    ),
                ),
                ("content", models.TextField()),
                ("description", models.TextField(blank=True)),
                ("use_count", models.IntegerField(default=0)),
                ("is_public", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prompts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("tags", models.ManyToManyField(blank=True, to="knowledge.tag")),
            ],
            options={
                "db_table": "knowledge_prompts",
                "ordering": ["-use_count", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TradingRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "rule_number",
                    models.IntegerField(help_text="Rule number for ordering."),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "rule_type",
                    models.CharField(
                        choices=[
                            ("ENTRY", "Entry Rule"),
                            ("EXIT", "Exit Rule"),
                            ("RISK", "Risk Rule"),
                            ("PSYCHOLOGY", "Psychology Rule"),
                            ("SYSTEM", "System Rule"),
                        ],
                        db_index=True,
                        default="SYSTEM",
                        max_length=15,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("CRITICAL", "Critical — Never Break"),
                            ("HIGH", "High — Rarely Break"),
                            ("MEDIUM", "Medium — Use Judgment"),
                            ("LOW", "Low — Guideline"),
                        ],
                        default="HIGH",
                        max_length=10,
                    ),
                ),
                ("times_broken", models.IntegerField(default=0)),
                ("last_broken_at", models.DateTimeField(blank=True, null=True)),
                (
                    "source_article",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rules",
                        to="knowledge.article",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trading_rules",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "knowledge_trading_rules",
                "ordering": ["rule_number"],
            },
        ),
        migrations.AddIndex(
            model_name="article",
            index=models.Index(
                fields=["category", "is_active"], name="knowledge_a_categor_8415fa_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="article",
            index=models.Index(
                fields=["user", "category"], name="knowledge_a_user_id_720dc5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tradingrule",
            index=models.Index(
                fields=["user", "rule_type"], name="knowledge_t_user_id_c84d33_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tradingrule",
            index=models.Index(
                fields=["user", "priority"], name="knowledge_t_user_id_3d6b9a_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="tradingrule",
            unique_together={("user", "rule_number")},
        ),
    ]
