from django.conf import settings
from django.db import models

from apps.market_data.models import Instrument
from shared.models import BaseModel


class PromptTemplate(BaseModel):
    """
    Stores reusable prompt templates for AI analysis.
    Templates use placeholders replaced at runtime.
    """

    TEMPLATE_TYPE_CHOICES = [
        ("MARKET_ANALYSIS", "Market Analysis"),
        ("SETUP_SCANNER", "Setup Scanner"),
        ("OPTION_CHAIN", "Option Chain Analysis"),
        ("RISK_ASSESSMENT", "Risk Assessment"),
        ("TRADE_REVIEW", "Trade Review"),
        ("NEWS_ANALYSIS", "News Analysis"),
    ]

    name = models.CharField(max_length=100, unique=True)
    template_type = models.CharField(
        max_length=20,
        choices=TEMPLATE_TYPE_CHOICES,
        db_index=True,
    )
    system_prompt = models.TextField(
        help_text="System prompt sent to the AI model.",
    )
    user_prompt_template = models.TextField(
        help_text="User prompt template with {placeholders}.",
    )
    model = models.CharField(
        max_length=50,
        default="claude-sonnet-4-6",
        help_text="AI model to use for this template.",
    )
    max_tokens = models.IntegerField(default=2000)
    temperature = models.FloatField(default=0.3)
    version = models.CharField(max_length=20, default="v1")
    is_default = models.BooleanField(default=False)

    class Meta:
        db_table = "ai_prompt_templates"
        ordering = ["name"]

    def __str__(self) -> str:
        return f"{self.name} ({self.template_type})"


class AnalysisSession(BaseModel):
    """
    Records a complete AI analysis session.
    Stores input, output, and metadata for journaling and backtesting.
    """

    STATUS_CHOICES = [
        ("PENDING", "Pending"),
        ("RUNNING", "Running"),
        ("COMPLETE", "Complete"),
        ("FAILED", "Failed"),
    ]

    SESSION_TYPE_CHOICES = [
        ("MARKET_ANALYSIS", "Market Analysis"),
        ("SETUP_SCANNER", "Setup Scanner"),
        ("OPTION_CHAIN", "Option Chain Analysis"),
        ("RISK_ASSESSMENT", "Risk Assessment"),
        ("TRADE_REVIEW", "Trade Review"),
    ]

    instrument = models.ForeignKey(
        Instrument,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="analysis_sessions",
    )
    template = models.ForeignKey(
        PromptTemplate,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
    )

    session_type = models.CharField(
        max_length=20,
        choices=SESSION_TYPE_CHOICES,
        db_index=True,
    )
    status = models.CharField(
        max_length=10,
        choices=STATUS_CHOICES,
        default="PENDING",
        db_index=True,
    )

    # Input
    timeframe = models.CharField(max_length=10, blank=True)
    market_context = models.JSONField(
        default=dict,
        help_text="Market data snapshot used as input.",
    )
    prompt_used = models.TextField(blank=True)

    # Output
    ai_response = models.TextField(blank=True)
    parsed_output = models.JSONField(
        default=dict,
        help_text="Structured output parsed from AI response.",
    )

    # Metadata
    model_used = models.CharField(max_length=50, blank=True)
    tokens_used = models.IntegerField(default=0)
    duration_ms = models.IntegerField(default=0)
    error_message = models.TextField(blank=True)

    session_time = models.DateTimeField(
        auto_now_add=True,
        db_index=True,
    )

    class Meta:
        db_table = "ai_analysis_sessions"
        ordering = ["-session_time"]
        indexes = [
            models.Index(fields=["session_type", "session_time"]),
            models.Index(fields=["status", "session_time"]),
        ]

    def __str__(self) -> str:
        symbol = self.instrument.symbol if self.instrument else "N/A"
        return f"{self.session_type} | {symbol} | {self.status}"


class AISignal(BaseModel):
    """
    A trading signal generated by the AI engine.
    Distinct from strategy signals — these are AI-reasoned outputs.
    """

    SIGNAL_CHOICES = [
        ("BUY", "Buy"),
        ("SELL", "Sell"),
        ("NEUTRAL", "Neutral"),
        ("NO_SETUP", "No Setup"),
        ("WATCH", "Watch"),
    ]

    CONFIDENCE_CHOICES = [
        ("HIGH", "High"),
        ("MEDIUM", "Medium"),
        ("LOW", "Low"),
    ]

    session = models.OneToOneField(
        AnalysisSession,
        on_delete=models.CASCADE,
        related_name="ai_signal",
    )
    instrument = models.ForeignKey(
        Instrument,
        on_delete=models.CASCADE,
        related_name="ai_signals",
    )

    # Owning user — needed for background outcome-tracking to know
    # whose Zerodha credentials to use when fetching real premiums.
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="ai_signals",
    )

    signal = models.CharField(
        max_length=10,
        choices=SIGNAL_CHOICES,
        db_index=True,
    )
    confidence = models.CharField(
        max_length=10,
        choices=CONFIDENCE_CHOICES,
        default="MEDIUM",
    )
    confidence_score = models.IntegerField(
        default=0,
        help_text="0-100 confidence score.",
    )

    price_at_signal = models.DecimalField(
        max_digits=12,
        decimal_places=2,
        null=True,
        blank=True,
    )
    target_price = models.DecimalField(
        max_digits=12,
        decimal_places=2,
        null=True,
        blank=True,
    )
    stop_loss = models.DecimalField(
        max_digits=12,
        decimal_places=2,
        null=True,
        blank=True,
    )

    # Real option contract attached to this signal.
    PRODUCT_CHOICES = [
        ("MIS", "Intraday"),
        ("NRML", "Carry Forward"),
    ]

    option_instrument = models.ForeignKey(
        Instrument,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="ai_signals_as_option",
        help_text="The specific option contract (CE/PE, strike, expiry) recommended for this signal.",
    )
    entry_premium = models.DecimalField(
        max_digits=12,
        decimal_places=2,
        null=True,
        blank=True,
        help_text="Real option premium (LTP) when this contract was attached.",
    )
    product = models.CharField(
        max_length=10,
        choices=PRODUCT_CHOICES,
        default="MIS",
        help_text="MIS = intraday, auto square-off ~15:15-15:20 IST. NRML = carry forward until target/stop or contract expiry.",
    )

    # Outcome tracking (Step 5) — filled in by the background task,
    # never fabricated. OPEN until real price data resolves it one way
    # or another.
    OUTCOME_CHOICES = [
        ("OPEN", "Open"),
        ("TARGET_HIT", "Target Hit"),
        ("STOP_HIT", "Stop Hit"),
        ("SQUARED_OFF", "Squared Off (MIS EOD)"),
        ("EXPIRED", "Expired (NRML)"),
    ]

    outcome_status = models.CharField(
        max_length=15,
        choices=OUTCOME_CHOICES,
        default="OPEN",
        db_index=True,
        help_text="Result of automated outcome tracking against the real option premium.",
    )
    outcome_price = models.DecimalField(
        max_digits=12,
        decimal_places=2,
        null=True,
        blank=True,
        help_text="Real premium at which tracking concluded.",
    )
    outcome_time = models.DateTimeField(
        null=True,
        blank=True,
        help_text="When tracking concluded.",
    )
    points_captured = models.DecimalField(
        max_digits=12,
        decimal_places=2,
        null=True,
        blank=True,
        help_text="outcome_price - entry_premium, in real option points.",
    )
    points_captured_pct = models.DecimalField(
        max_digits=8,
        decimal_places=2,
        null=True,
        blank=True,
        help_text="points_captured as a percentage of entry_premium.",
    )

    reasoning = models.TextField(
        help_text="AI reasoning for this signal.",
    )
    key_levels = models.JSONField(default=dict)
    risks = models.JSONField(default=list)
    signal_time = models.DateTimeField(db_index=True)

    class Meta:
        db_table = "ai_signals"
        ordering = ["-signal_time"]

    def __str__(self) -> str:
        return (
            f"{self.instrument.symbol} | "
            f"{self.signal} | "
            f"{self.confidence} | "
            f"{self.confidence_score}%"
        )