# Generated by Django 5.2.16 on 2026-07-19 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="phone_number",
            new_name="phone",
        ),
        migrations.AlterField(
            model_name="user",
            name="timezone",
            field=models.CharField(default="Asia/Kolkata", max_length=100),
        ),
    ]
