# Generated by Django 5.2.16 on 2026-07-21 19:11

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        (
            "market_data",
            "0003_alter_instrument_options_instrument_instrument_type_and_more",
        ),
        ("paper_trading", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="JournalEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("date", models.DateField(db_index=True)),
                (
                    "session",
                    models.CharField(
                        choices=[
                            ("PRE_MARKET", "Pre Market"),
                            ("INTRADAY", "Intraday"),
                            ("POST_MARKET", "Post Market"),
                            ("EOD", "End of Day"),
                        ],
                        default="EOD",
                        max_length=15,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "market_bias",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("BULLISH", "Bullish"),
                            ("BEARISH", "Bearish"),
                            ("NEUTRAL", "Neutral"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "market_notes",
                    models.TextField(
                        blank=True,
                        help_text="Market structure, key levels, observations.",
                    ),
                ),
                ("trades_taken", models.IntegerField(default=0)),
                ("winners", models.IntegerField(default=0)),
                ("losers", models.IntegerField(default=0)),
                (
                    "total_pnl",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "mood",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("CONFIDENT", "Confident"),
                            ("NEUTRAL", "Neutral"),
                            ("ANXIOUS", "Anxious"),
                            ("FEARFUL", "Fearful"),
                            ("GREEDY", "Greedy"),
                            ("DISCIPLINED", "Disciplined"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "emotion_notes",
                    models.TextField(
                        blank=True,
                        help_text="Emotional state and psychological observations.",
                    ),
                ),
                ("what_worked", models.TextField(blank=True)),
                ("what_didnt_work", models.TextField(blank=True)),
                ("lessons_learned", models.TextField(blank=True)),
                ("tomorrow_plan", models.TextField(blank=True)),
                (
                    "ai_review",
                    models.TextField(
                        blank=True,
                        help_text="AI-generated review of the journal entry.",
                    ),
                ),
                ("ai_reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "rating",
                    models.IntegerField(
                        default=0, help_text="Self-rating for the day 1-10."
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="journal_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "journal_entries",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="Lesson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("title", models.CharField(max_length=200)),
                ("content", models.TextField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("ENTRY", "Entry Rules"),
                            ("EXIT", "Exit Rules"),
                            ("RISK", "Risk Management"),
                            ("PSYCHOLOGY", "Psychology"),
                            ("STRATEGY", "Strategy"),
                            ("MARKET", "Market Observation"),
                            ("GENERAL", "General"),
                        ],
                        db_index=True,
                        default="GENERAL",
                        max_length=15,
                    ),
                ),
                (
                    "times_reinforced",
                    models.IntegerField(
                        default=1, help_text="How many times this lesson was relearned."
                    ),
                ),
                (
                    "is_rule",
                    models.BooleanField(
                        default=False, help_text="Mark as a hard trading rule."
                    ),
                ),
                (
                    "journal_entry",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lessons",
                        to="journal.journalentry",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lessons",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "journal_lessons",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TradeNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "setup_description",
                    models.TextField(
                        help_text="Describe the setup that triggered this trade."
                    ),
                ),
                ("entry_reason", models.TextField(blank=True)),
                ("exit_reason", models.TextField(blank=True)),
                (
                    "outcome",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("WIN", "Win"),
                            ("LOSS", "Loss"),
                            ("BREAKEVEN", "Breakeven"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "pnl",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("followed_plan", models.BooleanField(default=True)),
                (
                    "mistake_type",
                    models.CharField(
                        choices=[
                            ("NONE", "No Mistake"),
                            ("EARLY_ENTRY", "Early Entry"),
                            ("LATE_ENTRY", "Late Entry"),
                            ("EARLY_EXIT", "Early Exit"),
                            ("LATE_EXIT", "Late Exit"),
                            ("OVERSIZE", "Oversized Position"),
                            ("NO_SL", "No Stop Loss"),
                            ("REVENGE", "Revenge Trade"),
                            ("FOMO", "FOMO Trade"),
                            ("PLAN_DEVIATION", "Deviated from Plan"),
                        ],
                        default="NONE",
                        max_length=20,
                    ),
                ),
                ("mistake_notes", models.TextField(blank=True)),
                (
                    "improvement",
                    models.TextField(
                        blank=True, help_text="What would you do differently?"
                    ),
                ),
                ("screenshot_url", models.URLField(blank=True)),
                (
                    "instrument",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="market_data.instrument",
                    ),
                ),
                (
                    "journal_entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trade_notes",
                        to="journal.journalentry",
                    ),
                ),
                (
                    "trade",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="journal_note",
                        to="paper_trading.papertrade",
                    ),
                ),
            ],
            options={
                "db_table": "journal_trade_notes",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="journalentry",
            index=models.Index(
                fields=["user", "date"], name="journal_ent_user_id_0689ed_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="journalentry",
            unique_together={("user", "date", "session")},
        ),
        migrations.AddIndex(
            model_name="lesson",
            index=models.Index(
                fields=["user", "category"], name="journal_les_user_id_b96f1f_idx"
            ),
        ),
    ]
