# Generated by Django 5.2.16 on 2026-07-21 18:57

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        (
            "market_data",
            "0003_alter_instrument_options_instrument_instrument_type_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PaperAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=1000000.0,
                        help_text="Available cash balance.",
                        max_digits=15,
                    ),
                ),
                (
                    "initial_balance",
                    models.DecimalField(
                        decimal_places=2, default=1000000.0, max_digits=15
                    ),
                ),
                (
                    "used_margin",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "total_pnl",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Cumulative realized PnL.",
                        max_digits=15,
                    ),
                ),
                (
                    "today_pnl",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                ("total_trades", models.IntegerField(default=0)),
                ("winning_trades", models.IntegerField(default=0)),
                ("losing_trades", models.IntegerField(default=0)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="paper_account",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "paper_accounts",
            },
        ),
        migrations.CreateModel(
            name="PaperPosition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "direction",
                    models.CharField(
                        choices=[("LONG", "Long"), ("SHORT", "Short")], max_length=5
                    ),
                ),
                ("quantity", models.IntegerField()),
                ("average_price", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "last_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "unrealized_pnl",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "realized_pnl",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("open_time", models.DateTimeField(auto_now_add=True)),
                ("close_time", models.DateTimeField(blank=True, null=True)),
                ("is_open", models.BooleanField(db_index=True, default=True)),
                ("product", models.CharField(default="MIS", max_length=5)),
                ("tag", models.CharField(blank=True, max_length=50)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="positions",
                        to="paper_trading.paperaccount",
                    ),
                ),
                (
                    "instrument",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="paper_positions",
                        to="market_data.instrument",
                    ),
                ),
            ],
            options={
                "db_table": "paper_positions",
                "ordering": ["-open_time"],
            },
        ),
        migrations.CreateModel(
            name="PaperTrade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("direction", models.CharField(max_length=5)),
                ("quantity", models.IntegerField()),
                ("entry_price", models.DecimalField(decimal_places=2, max_digits=12)),
                ("exit_price", models.DecimalField(decimal_places=2, max_digits=12)),
                ("entry_time", models.DateTimeField()),
                ("exit_time", models.DateTimeField()),
                (
                    "pnl",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Realized PnL for this trade.",
                        max_digits=12,
                    ),
                ),
                (
                    "pnl_pct",
                    models.DecimalField(decimal_places=4, default=0, max_digits=8),
                ),
                (
                    "brokerage",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                (
                    "net_pnl",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="PnL after brokerage.",
                        max_digits=12,
                    ),
                ),
                ("product", models.CharField(default="MIS", max_length=5)),
                ("tag", models.CharField(blank=True, max_length=50)),
                ("notes", models.TextField(blank=True)),
                ("strategy_signal", models.CharField(blank=True, max_length=50)),
                ("ai_signal", models.CharField(blank=True, max_length=50)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trades",
                        to="paper_trading.paperaccount",
                    ),
                ),
                (
                    "instrument",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="paper_trades",
                        to="market_data.instrument",
                    ),
                ),
                (
                    "position",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="trade",
                        to="paper_trading.paperposition",
                    ),
                ),
            ],
            options={
                "db_table": "paper_trades",
                "ordering": ["-exit_time"],
            },
        ),
        migrations.CreateModel(
            name="PaperOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "order_type",
                    models.CharField(
                        choices=[
                            ("MARKET", "Market"),
                            ("LIMIT", "Limit"),
                            ("SL", "Stop Loss"),
                            ("SL_M", "Stop Loss Market"),
                        ],
                        default="MARKET",
                        max_length=10,
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[("BUY", "Buy"), ("SELL", "Sell")],
                        db_index=True,
                        max_length=5,
                    ),
                ),
                (
                    "product",
                    models.CharField(
                        choices=[
                            ("MIS", "Intraday (MIS)"),
                            ("NRML", "Normal (NRML)"),
                            ("CNC", "Delivery (CNC)"),
                        ],
                        default="MIS",
                        max_length=5,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("OPEN", "Open"),
                            ("COMPLETE", "Complete"),
                            ("CANCELLED", "Cancelled"),
                            ("REJECTED", "Rejected"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                ("quantity", models.IntegerField()),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Limit price. 0 for market orders.",
                        max_digits=12,
                    ),
                ),
                (
                    "trigger_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Trigger price for SL orders.",
                        max_digits=12,
                    ),
                ),
                (
                    "average_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Actual execution price.",
                        max_digits=12,
                    ),
                ),
                ("filled_quantity", models.IntegerField(default=0)),
                ("pending_quantity", models.IntegerField(default=0)),
                ("order_time", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("execution_time", models.DateTimeField(blank=True, null=True)),
                (
                    "tag",
                    models.CharField(
                        blank=True,
                        help_text="Tag to identify order source e.g. strategy name.",
                        max_length=50,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("reject_reason", models.TextField(blank=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to="paper_trading.paperaccount",
                    ),
                ),
                (
                    "instrument",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="paper_orders",
                        to="market_data.instrument",
                    ),
                ),
            ],
            options={
                "db_table": "paper_orders",
                "ordering": ["-order_time"],
                "indexes": [
                    models.Index(
                        fields=["account", "status"],
                        name="paper_order_account_5efd27_idx",
                    ),
                    models.Index(
                        fields=["account", "order_time"],
                        name="paper_order_account_72b9b5_idx",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="paperposition",
            index=models.Index(
                fields=["account", "is_open"], name="paper_posit_account_ccd9b9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paperposition",
            index=models.Index(
                fields=["account", "instrument"], name="paper_posit_account_88d0f2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="papertrade",
            index=models.Index(
                fields=["account", "exit_time"], name="paper_trade_account_729356_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="papertrade",
            index=models.Index(
                fields=["instrument", "exit_time"],
                name="paper_trade_instrum_54f692_idx",
            ),
        ),
    ]
